### ISSUE TITLE
Question regarding pvalues vs. adj.pvalues

### ISSUE THREAD

**Issue by liorlobel** [Vitek-Lab/MSstats#95] opened 2023-03-12 10:44 UTC
Dear Vitek Lab, 

Thanks for developing MSstats. 

I have a question regarding adj.pvalues.
It might be my own confusion, but I see some nicely distributed pvalues (see self-generated volcano plot below), but when I'm graphing the adj.pvalues I get weird results - see both my self-generated and MSstats-generated volcano plots.

One thing that is confusing is that when sorting the adj.pvalues I see a lot of 0's, while the pvalues have normal non-zero values.

I will greatly appreciate any advice, 

Best,

Lior

P values
![image](https://user-images.githubusercontent.com/8280386/224539253-25748f24-2abc-4199-8f8f-a91dd5adbba3.png)

Adj.pvalues 
![image](https://user-images.githubusercontent.com/8280386/224539283-a03e6429-3351-4a33-8c8b-f089f2bfc9f9.png)

MSstats - groupComparisonPlots
![image](https://user-images.githubusercontent.com/8280386/224539599-c8e3ac9c-cc45-470f-8daf-8ce50649304e.png)

**Comment by liorlobel** [comment] 2023-03-12 11:10
When I adjust the pvalues using the p.adjust function, I get non-zero values. The top, on-axis, points disappear.

**Comment by mstaniak** [comment] 2023-03-13 15:35
Hi,
thanks for reporting the problem, can you provide a subset of data to reproduce the problem? 
(Data can be anonymized by changing protein, peptide, condition labels if needed, only the structure matters)

**Comment by mstaniak** [comment] 2023-04-03 16:42
Hi,

this update should fix the problem: https://github.com/Vitek-Lab/MSstatsConvert/tree/hotfix-diann-na
it will make it to Bioconductor version soon

**Comment by liorlobel** [comment] 2023-04-03 18:18
Thanks! Will try

**Comment by mstaniak** [comment] 2023-04-03 22:22
Hi, sorry, I accidentally sent that message to a wrong issue. Could you kindly share a small data sample that reproduces your issue?

**Comment by liorlobel** [comment] 2023-04-18 09:00
Thanks for the reply, and sorry for the late response. 
Please see the attached file. 
Best, 

Lior
[MSstats_to_github.csv](https://github.com/Vitek-Lab/MSstats/files/11259947/MSstats_to_github.csv)

**Comment by luizalmeida93** [comment] 2023-04-19 21:07
Hi Dr. Staniak,

I have a similar issue with some of my analyses too. It already happened with label-free (MSstats) or TMT data (MSstatsTMT). I am attaching one of them as an example.

This is a label-free study, with proteomics search performed by MaxQuant.
Here are the parameters I used for the conversion to MSstats format:

`MaxQtoMSstatsFormat(evidence=evidence,
                             annotation=annot,
                             proteinGroups=proteinGroups,
                             removeProtein_with1Peptide=TRUE,
                             proteinID = "Proteins")`

The data is here: [DataForGitHub.csv](https://github.com/Vitek-Lab/MSstats/files/11277571/DataForGitHub.csv)

Take a look at the histogram below showing the distribution of pvalues and adj.pvalues for group1 vs group2:

![image](https://user-images.githubusercontent.com/59628759/233199805-03900d2f-f2d2-4b25-868a-e6fd72cac029.png)

Please, let me know if you need any additional data, and thank you for your help.

**Comment by mstaniak** [comment] 2023-04-20 11:13
Hi,
thanks for providing example data, I will get back to you as soon as possible

**Comment by mstaniak** [comment] 2023-04-21 12:10
Hi,
@liorlobel which correction method did you use for your comparison of adjusted by MSstats vs p.adjust? Are the cases with a non-zero vs zero value the ones with "oneConditionMissing" message in the "issue" column of groupComparison output?

@luizalmeida93 the correction is fine. It's just that BH produces many repeated p-values. If you look at adj. pvalues for all contrasts together, you will see more variability and some significant results.

**Comment by liorlobel** [comment] 2023-04-30 11:49
Hi, 

I used the default MSstats option. For the p.adjust I used BH FDR.

Thanks!

**Comment by luizalmeida93** [comment] 2024-01-18 17:11
> @luizalmeida93 the correction is fine. It's just that BH produces many repeated p-values. If you look at adj. pvalues for all contrasts together, you will see more variability and some significant results.

@mstaniak sorry for reviving this topic, but I am troubleshooting a few things and fell in this rabbit hole again. What did you mean by "look at adj. pvalues for all contrasts together"? I am assuming you ran a different contrast matrix than just two groups, each with a "1" or "-1". Can you provide an example?

**Comment by mstaniak** [comment] 2024-02-29 23:40
Sorry for a delayed answer. If I remember correctly - yes. BH correction involves a cumulative minimum, so in some "unlucky" cases it might produces a visible amount of identical adjusted p-values.
In your example correction is OK and it looks like a sort of an artifact of a particular data set and comparison. If you look at p-values from all contrasts in a pairwise comparisons matrix, you'll see more variability in p-values.

**Comment by mstaniak** [comment] 2024-02-29 23:43
Looking at this again, I think the BioReplicate column in @liorlobel 's data is wrong - if this is group comparison design, BioReplicate labels should be nested in Conditions.

**Comment by mstaniak** [comment] 2024-07-31 15:04
closing this issue, please re-open if needed

**Closed by mstaniak** 2024-07-31 15:04 UTC
